### ISSUE TITLE
Move task level variable

### ISSUE THREAD

**Issue by pratikbin** [polkachu/cosmos-validators#11]
Hello, Thanks for amazing contribution to #web3.

We can improve from `old,new` to `key`:`value` based

From

https://github.com/polkachu/cosmos-validators/blob/7a2bec2ea2aedb0d0b3df1432725bd0b13647359/roles/node_configure/tasks/main.yml#L14-L39

To 

```yaml
vars:
  config_changes:
    'laddr = "tcp://0.0.0.0:26656"': 'laddr = "tcp://0.0.0.0:{{ custom_port_prefix }}656"'

...

- name: Adjust config.toml port when needed
  lineinfile:
    path: '{{ user_dir }}/{{ folder }}/config/config.toml'
    regexp: '{{ item.key }}'
    line: '{{ item.value }}'
```
