### ISSUE TITLE
fix: run ufw commands only if prepare is true in node_launch role

### ISSUE THREAD

**Issue by pratikbin** [polkachu/cosmos-validators#12]
Run ufw command only if prepare is true in node_launch role. 

```ignore_errors: (prepare is defined) and (prepare|bool is false)```

So

### Old

https://github.com/polkachu/cosmos-validators/blob/9a4e54e7c0a784ebf629b7459e27ebf384d74ca9/roles/node_launch/tasks/main.yml#L2-L8

### New

```yaml
 - name: open prometheus port 
   become: true 
   command: 'ufw allow {{ custom_port_prefix }}660/tcp'
   ignore_errors: (prepare is defined) and (prepare|bool is false)

 - name: open p2p port 
   become: true 
   command: 'ufw allow {{ custom_port_prefix }}656/tcp'
   ignore_errors: (prepare is defined) and (prepare|bool is false)
```
